# Generated by Django 5.2.12 on 2026-04-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback_admin_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='content_zh',
            field=models.TextField(blank=True, null=True, verbose_name='中文内容'),
        ),
    ]
