"""
Django settings for SheXingDjango project.

Generated by 'django-admin startproject' using Django 3.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from openai import OpenAI
import uuid
import time
import requests

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m00f^=6ro)_m9iyj)rwre+8ua51nym6-hy$tqb(j(^u-)ssm78'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost', '192.168.165.206']
# Application definition

INSTALLED_APPS = [
    'admin_interface',  # 必须在此位置
    'colorfield',      # 必须在此位置
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework.apps.RestFrameworkConfig',
    'corsheaders.apps.CorsHeadersAppConfig',
    'users',
    'dorm',
    'attendance',
    'django_crontab',
    'channels',

]

ASGI_APPLICATION = 'SheXingDjango.asgi.application'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SheXingDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SheXingDjango.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 跨域设置（开发阶段允许所有来源）
CORS_ALLOW_ALL_ORIGINS = True

# REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',  # 使用JWT认证
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',  # 默认需要登录
    ]
}

# JWT 配置（设置token有效期）
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=365),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=365),
}

# 媒体文件配置（用于上传图片）
import os

MEDIA_URL = '/media/'
# noinspection PyUnresolvedReferences
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 告诉Django使用我们自定义的用户模型
AUTH_USER_MODEL = 'users.User'


CRONJOBS = [
    # 每天 21:50 运行一次（可以根据需要调整，建议在辅导员设置的开始时间之前一点）
    ('50 21 * * *', 'attendance.cron.create_auto_clock_issues', '>> ' + os.path.join(BASE_DIR, 'logs/cron.log'))
]

# ========== 豆包AI配置 ==========
# 从火山引擎控制台获取的API Key
DOUBAO_API_KEY = '61e8ee1d-87b3-46ac-ad9e-40554c91e48e'

# 推理接入点ID
DOUBAO_ENDPOINT_ID = 'ep-20260331153128-t77w2'

# 是否使用Mock模式（开发时先用Mock，拿到真实Key后改为False）
DOUBAO_USE_MOCK = False  # 先设为True，等API Key配置好再改False

# 模型名称（使用视觉模型）
DOUBAO_MODEL = 'doubao-1-5-vision-pro-32k-250115'
DOUBAO_TEXT_MODEL = 'doubao-1-5-vision-pro-32k-250115'
DOUBAO_TRANSLATION_MODEL = 'doubao-1-5-vision-pro-32k-250115'


# 原有的 DOUBAO_API_KEY 保持不变，图像生成和文本生成共用同一个 Key

# ========== 蓝心大模型配置（用于文本生成）==========
# 蓝心大模型 API 配置
BLUELM_API_URL = "https://api-ai.vivo.com.cn/v1/chat/completions"  # 蓝心大模型API地址
BLUELM_API_KEY = "sk-xuanji-2026714479-THdMeGpXZ25oWm5QdEFQVw=="        # 待申请的真实 API Key
BLUELM_USE_MOCK = False     # 开发阶段使用模拟数据，等拿到真实 Key 后改为 False
BLUELM_MODEL = "Doubao-Seed-2.0-lite" # 蓝心大模型名称（参考官方文档确定）



# vivo DeepSeek 配置（新接口）
VIVO_DEEPSEEK_API_KEY = 'sk-xuanji-2026714479-THdMeGpXZ25oWm5QdEFQVw=='      # 替换成你在 vivo 平台申请的 AppKey
VIVO_DEEPSEEK_USE_MOCK = False            # 关闭 Mock
VIVO_DEEPSEEK_MODEL = 'Volc-DeepSeek-V3.2'

ASGI_APPLICATION = 'SheXingDjango.asgi.application'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')