# Generated by Django 5.2.12 on 2026-04-08 02:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DormInspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50, verbose_name='楼栋')),
                ('floor', models.CharField(max_length=20, verbose_name='楼层')),
                ('room', models.CharField(max_length=20, verbose_name='寝室号')),
                ('grade', models.CharField(choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级')], max_length=1, verbose_name='等级')),
                ('regulations', models.JSONField(verbose_name='违反条例')),
                ('images', models.JSONField(default=list, verbose_name='图片列表')),
                ('inspect_time', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='班级')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_records', to=settings.AUTH_USER_MODEL, verbose_name='检查人')),
            ],
            options={
                'ordering': ['-inspect_time'],
            },
        ),
        migrations.CreateModel(
            name='PowerInspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50, verbose_name='楼栋')),
                ('floor', models.CharField(max_length=20, verbose_name='楼层')),
                ('room', models.CharField(max_length=20, verbose_name='寝室号')),
                ('item_name', models.CharField(max_length=100, verbose_name='违规物品')),
                ('description', models.TextField(verbose_name='违规说明')),
                ('images', models.JSONField(verbose_name='图片列表')),
                ('class_name', models.CharField(blank=True, max_length=50, verbose_name='班级')),
                ('inspect_time', models.DateTimeField(auto_now_add=True, verbose_name='检查时间')),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='检查人')),
            ],
        ),
    ]
