# Generated by Django 5.2.12 on 2026-04-15 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DormWarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(max_length=50, verbose_name='楼栋')),
                ('room', models.CharField(max_length=20, verbose_name='寝室号')),
                ('trigger_reason', models.TextField(verbose_name='触发原因')),
                ('risk_level', models.CharField(choices=[('high', '高风险'), ('medium', '中风险'), ('low', '低风险')], max_length=10, verbose_name='风险等级')),
                ('ai_suggestion', models.TextField(verbose_name='AI预警建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='预警时间')),
                ('is_handled', models.BooleanField(default=False, verbose_name='是否已处理')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_warnings', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '寝室预警',
                'verbose_name_plural': '寝室预警',
                'ordering': ['-created_at'],
            },
        ),
    ]
