# Generated by Django 5.2.12 on 2026-04-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0002_dormwarning'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(verbose_name='周起始日期')),
                ('week_end', models.DateField(verbose_name='周结束日期')),
                ('total', models.IntegerField(verbose_name='检查宿舍总数')),
                ('avg_score', models.FloatField(verbose_name='平均分')),
                ('grade_a_count', models.IntegerField(verbose_name='A级宿舍数')),
                ('grade_b_count', models.IntegerField(verbose_name='B级宿舍数')),
                ('grade_c_count', models.IntegerField(verbose_name='C级宿舍数')),
                ('top_violations', models.JSONField(default=list, verbose_name='高频违规项')),
                ('report_text', models.TextField(verbose_name='周报正文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '卫生周报',
                'verbose_name_plural': '卫生周报',
                'ordering': ['-week_start'],
            },
        ),
    ]
