# Generated by Django 5.2.12 on 2026-03-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClockIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='考勤地点')),
                ('location', models.JSONField(verbose_name='经纬度')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_time', models.DateTimeField(auto_now_add=True, verbose_name='打卡时间')),
                ('address', models.CharField(max_length=255, verbose_name='打卡地点')),
                ('location', models.JSONField(verbose_name='打卡经纬度')),
                ('status', models.CharField(default='normal', max_length=20, verbose_name='状态')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('reason', models.TextField(verbose_name='请假原因')),
                ('proof_images', models.JSONField(blank=True, default=list, verbose_name='证明材料')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, verbose_name='拒绝原因')),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
