# Generated by Django 5.2.12 on 2026-03-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='type',
            field=models.CharField(choices=[('leave', '请假'), ('supplement', '补卡')], default='leave', max_length=20, verbose_name='申请类型'),
            preserve_default=False,
        ),
    ]
