# Generated by Django 5.2.12 on 2026-03-19 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_leave_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', '病假'), ('personal', '事假'), ('night_out', '夜不归寝事假'), ('other', '其他')], max_length=20, null=True, verbose_name='请假类型'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('holiday', '节假日'), ('vacation', '寒暑假'), ('intern', '实习')], max_length=20, verbose_name='备案类型')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='去向/地点')),
                ('emergency_contact', models.CharField(max_length=50, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(max_length=20, verbose_name='紧急联系电话')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
        ),
    ]
