# Generated by Django 5.2.12 on 2026-03-19 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leave_leave_type_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoClockSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='是否启用自动发布')),
                ('address', models.CharField(max_length=255, verbose_name='考勤地点')),
                ('location', models.JSONField(help_text='格式 [经度, 纬度]', verbose_name='经纬度')),
                ('start_time', models.TimeField(help_text='例如 22:00:00', verbose_name='每日开始时间')),
                ('end_time', models.TimeField(help_text='例如 23:59:59', verbose_name='每日结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counselor', models.OneToOneField(limit_choices_to={'role': 'counselor'}, on_delete=django.db.models.deletion.CASCADE, related_name='auto_clock_setting', to=settings.AUTH_USER_MODEL, verbose_name='辅导员')),
            ],
            options={
                'verbose_name': '自动考勤设置',
                'verbose_name_plural': '自动考勤设置',
            },
        ),
    ]
