# Generated by Django 5.2.12 on 2026-03-30 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_autoclocksetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('send_to', models.CharField(choices=[('all', '全体'), ('building', '指定楼栋'), ('class', '指定班级'), ('user', '指定用户')], default='all', max_length=50)),
                ('target_building', models.CharField(blank=True, max_length=50, null=True)),
                ('target_class', models.CharField(blank=True, max_length=50, null=True)),
                ('send_time', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('content', models.TextField(verbose_name='模板内容')),
                ('category', models.CharField(choices=[('notice', '公告'), ('warning', '预警'), ('reminder', '提醒'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='分类')),
                ('variables', models.JSONField(blank=True, default=list, help_text='例如 ["学生姓名", "寝室号"]', verbose_name='变量列表')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '通知模板',
                'verbose_name_plural': '通知模板',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_time', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('is_urged', models.BooleanField(default=False, verbose_name='是否已催办')),
                ('urged_count', models.IntegerField(default=0, verbose_name='催办次数')),
                ('urged_last_time', models.DateTimeField(blank=True, null=True, verbose_name='最后催办时间')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='attendance.notification', verbose_name='通知')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户通知',
                'verbose_name_plural': '用户通知',
                'unique_together': {('user', 'notification')},
            },
        ),
    ]
