# Generated by Django 5.2.12 on 2026-04-08 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_notification_notificationtemplate_usernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
