# Generated by Django 5.2.12 on 2026-04-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_notification_target_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='content_en',
            field=models.TextField(blank=True, null=True, verbose_name='英文内容'),
        ),
    ]
