# Generated by Django 5.2.12 on 2026-05-07 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_notification_content_en'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clockissue',
            options={'verbose_name': '考勤任务', 'verbose_name_plural': '考勤任务'},
        ),
        migrations.AlterModelOptions(
            name='clockrecord',
            options={'verbose_name': '打卡记录', 'verbose_name_plural': '打卡记录'},
        ),
        migrations.AlterModelOptions(
            name='leave',
            options={'verbose_name': '请假记录', 'verbose_name_plural': '请假记录'},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': '备案登记', 'verbose_name_plural': '备案登记'},
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='发送者')),
            ],
            options={
                'verbose_name': '私信',
                'verbose_name_plural': '私信',
                'ordering': ['created_at'],
            },
        ),
    ]
